// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	accesstoken2 "github.com/evenyosua18/auth2/app/repository/authdb/accesstoken"
	endpoint2 "github.com/evenyosua18/auth2/app/repository/authdb/endpoint"
	"github.com/evenyosua18/auth2/app/repository/authdb/oauthclient"
	"github.com/evenyosua18/auth2/app/repository/authdb/refreshtoken"
	"github.com/evenyosua18/auth2/app/repository/authdb/user"
	"github.com/evenyosua18/auth2/app/usecase/accesstoken"
	"github.com/evenyosua18/auth2/app/usecase/endpoint"
	oauthclient2 "github.com/evenyosua18/auth2/app/usecase/oauthclient"
	"github.com/evenyosua18/auth2/app/usecase/registration"
	"github.com/evenyosua18/auth2/app/utils/db"
)

// Injectors from access_token_usecase.go:

func InitializeAccessTokenUsecase(connection *db.MongoConnection) accesstoken.IAccessTokenUsecase {
	iOauthClientRepository := oauthclient.NewOauthClientRepository(connection)
	iUserRepository := user.NewUserRepository(connection)
	iAccessTokenRepository := accesstoken2.NewAccessTokenRepository(connection)
	iRefreshTokenRepository := refreshtoken.NewRefreshTokenRepository(connection)
	iAccessTokenUsecase := accesstoken.NewAccessTokenUsecase(iOauthClientRepository, iUserRepository, iAccessTokenRepository, iRefreshTokenRepository)
	return iAccessTokenUsecase
}

// Injectors from oauth_client_usecase.go:

func InitializeOauthClientUsecase(connection *db.MongoConnection) oauthclient2.IOauthClientUsecase {
	iOauthClientRepository := oauthclient.NewOauthClientRepository(connection)
	iOauthClientUsecase := oauthclient2.NewOauthClientUsecase(iOauthClientRepository)
	return iOauthClientUsecase
}

// Injectors from registration_usecase.go:

func InitializeRegistrationUserUsecase(connection *db.MongoConnection) registration.IRegistrationUserUsecase {
	iUserRepository := user.NewUserRepository(connection)
	iAccessTokenRepository := accesstoken2.NewAccessTokenRepository(connection)
	iRefreshTokenRepository := refreshtoken.NewRefreshTokenRepository(connection)
	iRegistrationUserUsecase := registration.NewRegistrationUserUsecase(iUserRepository, iAccessTokenRepository, iRefreshTokenRepository)
	return iRegistrationUserUsecase
}

func InitializeRegistrationEndpointUsecase(connection *db.MongoConnection) endpoint.IRegistrationEndpointUsecase {
	iEndpointRepository := endpoint2.NewEndpointRepository(connection)
	iRegistrationEndpointUsecase := endpoint.NewUsecaseRegistrationEndpoint(iEndpointRepository)
	return iRegistrationEndpointUsecase
}
